version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - java --version
      - $(aws ecr get-login --no-include-email)
      - docker pull postgres:11.6-alpine
      - docker pull redis:6.2.0
      - docker pull openzipkin/zipkin:latest
      - docker pull elasticsearch:7.4.2
      - docker pull amazoncorretto:11
      - docker images
  build:
    commands:
      - docker-compose up -d
      - sleep 20s
      - ./gradlew clean test
      - docker build . -t $CONTAINER_REPOSITORY_URL:latest -t $CONTAINER_REPOSITORY_URL:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - docker push $CONTAINER_REPOSITORY_URL:$CODEBUILD_BUILD_NUMBER
      - docker push $CONTAINER_REPOSITORY_URL:latest