version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - java --version
      - $(aws ecr get-login --no-include-email)
      - docker pull postgres:11.10-alpine
      - docker pull redis:6.2.0
      - docker pull elasticsearch:7.9.1
      - docker pull amazoncorretto:11
      - docker images
  build:
    commands:
      - docker-compose up -d
      - sleep 20s
      - ./gradlew clean test
      - ./gradlew bootBuildImage
      - docker tag docker.io/library/headhunter-api:latest $CONTAINER_REPOSITORY_URL:latest
      - docker tag docker.io/library/headhunter-api:latest $CONTAINER_REPOSITORY_URL:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - docker push $CONTAINER_REPOSITORY_URL:$CODEBUILD_BUILD_NUMBER
      - docker push $CONTAINER_REPOSITORY_URL:latest