version: '3.7'
services:
  postgres:
    image: postgres:11.10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_hunter
    ports:
      - 5432:5432

  elasticsearch:
    image: elasticsearch:7.9.1
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - discovery.type=single-node

  redis:
    image: redis:6.2.0
    ports:
      - 6379:6379

  postgres_keycloak:
    image: postgres:11.10-alpine
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_secret
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 15

  keycloak:
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    image: quay.io/keycloak/keycloak:12.0.4
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_keycloak
      DB_DATABASE: postgres
      DB_USER: keycloak
      DB_PASSWORD: keycloak_secret
      PROXY_ADDRESS_FORWARDING: "true"