version: '3.7'
services:
  postgres_integration:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_USER: mn_integ_hh_username
      POSTGRES_PASSWORD: mn_integ_hh_password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mn_integ_hh_username" ]
      interval: 15s
      timeout: 5s
      retries: 10

  elasticsearch_integration:
    image: elasticsearch:7.9.1
    depends_on:
      - postgres_integration
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - discovery.type=single-node
    healthcheck:
      test: [ "CMD-SHELL", "curl localhost:9200/_cluster/health --fail" ]
      interval: 15s
      timeout: 5s
      retries: 10

  redis_integration:
    image: redis:6.2.0
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 30

  postgres_keycloak_integration:
    image: postgres:11.10-alpine
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_secret
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloakintegration:
    depends_on:
      postgres_keycloak_integration:
        condition: service_healthy
    image: quay.io/keycloak/keycloak:12.0.4
    ports:
      - 8081:8080
    healthcheck:
      test: [ "CMD-SHELL", "curl localhost:8080/auth/realms/master --fail" ]
      interval: 30s
      timeout: 5s
      retries: 15
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_keycloak_integration
      DB_DATABASE: postgres
      DB_USER: keycloak
      DB_PASSWORD: keycloak_secret
      PROXY_ADDRESS_FORWARDING: "true"
      FRONTEND_URL: "http://keycloakintegration:8080"
      FORCE_BACKEND_URL_TO_FRONTEND_URL: "true"

  application:
    image: "docker.io/library/headhunter-api:latest"
    entrypoint: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/home/app/application.jar"]
    depends_on:
      redis_integration:
        condition: service_healthy
      elasticsearch_integration:
        condition: service_healthy
      keycloakintegration:
        condition: service_healthy
      postgres_integration:
        condition: service_healthy
    environment:
      DEBUG: "true"
      SERVER_PORT: "9999"
      SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_ENDPOINTS: "elasticsearch_integration"
      SPRING_ELASTICSEARCH_REST_URIS: "https://elasticsearch_integration:9300"
      SPRING_REDIS_HOST: "redis_integration"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres_integration:5432/postgres?currentSchema=public"
      SPRING_DATASOURCE_USERNAME: "mn_integ_hh_username"
      SPRING_DATASOURCE_PASSWORD: "mn_integ_hh_password"
      SPRING_R2DBC_URL: "r2dbc:postgresql://postgres_integration/postgres?currentSchema=public"
      SPRING_R2DBC_USERNAME: "mn_integ_hh_username"
      SPRING_R2DBC_PASSWORD: "mn_integ_hh_password"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloakintegration:8080/auth/realms/master"
    ports:
      - "8080:9999"
      - "5005:5005"