version: '3.7'
services:
  postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_hunter
    ports:
      - 5432:5432
  elasticsearch:
    image: elasticsearch:7.9.1
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - discovery.type=single-node
  redis:
    image: redis:6.2.0
    ports:
      - 6379:6379
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: secret_hunter
      PROXY_ADDRESS_FORWARDING: "true"
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411