version: '3.7'
services:
  postgres_integration:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_USER: mn_integ_hh_username
      POSTGRES_PASSWORD: mn_integ_hh_password
    ports:
      - 5432:5432
  elasticsearch_integration:
    image: elasticsearch:7.9.1
    depends_on:
      - postgres_integration
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - discovery.type=single-node
  redis_integration:
    image: redis:6.2.0
    depends_on:
      - elasticsearch_integration
    ports:
      - 6379:6379
  postgres_keycloak_integration:
    image: postgres:11.10-alpine
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_secret
  keycloak_integration:
    depends_on:
      - postgres_keycloak_integration
    image: quay.io/keycloak/keycloak:12.0.4
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_keycloak_integration
      DB_DATABASE: postgres
      DB_USER: keycloak
      DB_PASSWORD: keycloak_secret
      PROXY_ADDRESS_FORWARDING: "true"
  application:
    image: "docker.io/library/headhunter-api:latest"
    entrypoint: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/home/app/application.jar"]
    depends_on:
      - keycloak_integration
    environment:
      DEBUG: "true"
      SERVER_PORT: "9999"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
      SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_ENDPOINTS: "elasticsearch_integration"
      SPRING_ELASTICSEARCH_REST_URIS: "https://elasticsearch_integration:9300"
      SPRING_REDIS_HOST: "redis_integration"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres_integration:5432/postgres?currentSchema=public"
      SPRING_DATASOURCE_USERNAME: "mn_integ_hh_username"
      SPRING_DATASOURCE_PASSWORD: "mn_integ_hh_password"
      SPRING_R2DBC_URL: "r2dbc:postgresql://postgres_integration/postgres?currentSchema=public"
      SPRING_R2DBC_USERNAME: "mn_integ_hh_username"
      SPRING_R2DBC_PASSWORD: "mn_integ_hh_password"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak_integration:8080/auth/realms/master"
    ports:
      - "8080:9999"
      - "5005:5005"