spring:
  application:
    name: headhunter-api
  cloud:
    service-registry:
      auto-registration:
        enabled: false
    discovery:
      enabled: false
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
          useSsl: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: secret_hunter
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: secret_hunter
    properties:
      ssl: true
      sslMode: REQUIRE
  elasticsearch:
    rest:
      uris: http://localhost:9200
      username: ''
      password: ''
  redis:
    host: localhost
    port: 6379
  sleuth:
    propagation:
      type: aws
  zipkin:
    base-url: http://localhost:9411
    locator:
      discovery:
        enabled: false
    discovery-client-enabled: false

management:
  endpoint:
    health:
      show-details: always
