spring:
  application:
    name: headhunter-api
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
          useSsl: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: secret_hunter
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: secret_hunter
    properties:
      ssl: true
      sslMode: REQUIRE
  elasticsearch:
    rest:
      uris: http://localhost:9200
      username: ''
      password: ''
  redis:
    host: localhost
    port: 6379
  security:
    #https://docs.spring.io/spring-security/site/docs/5.2.0.M2/reference/html/webflux-oauth2.html#webflux-oauth2-resource-server
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8081/auth/realms/master"
